
from .plugin_xgfabric   import PluginXGFabric  # noqa: F401
from .plugin_queue_info import PluginQueueInfo  # noqa: F401
from .plugin_sysinfo    import PluginSysInfo  # noqa: F401

# Optional plugins with external dependencies
try:
    from .plugin_lucid import PluginLucid  # noqa: F401
except ImportError:
    pass

try:
    from .plugin_psij import PluginPSIJ  # noqa: F401
except ImportError:
    pass

try:
    from .plugin_rhapsody import PluginRhapsody  # noqa: F401
except ImportError:
    pass

from .plugin_base           import Plugin  # noqa: F401
from .plugin_session_base   import PluginSession  # noqa: F401
from .ui_schema             import (UIConfig, UIForm, UIField,  # noqa: F401
                                    UIMonitor, UINotifications,
                                    ui_config_to_dict)

from .service           import EdgeService  # noqa: F401
from .client            import BridgeClient, EdgeClient, PluginClient  # noqa: F401

# _version.py is generated by setup.py at install time and is
# git-ignored.  When running from an uninstalled source tree the
# import will fail and we fall back to dev markers.
try:
    from ._version import version, version_detail  # noqa: F401
except ImportError:
    version        = 'unknown'
    version_detail = 'unknown'

__version__ = version
